services:

  demo-app-1:
    image: varoon10/prometheus-demo-service
    ports: 
      - 8080:8080
    container_name: demo-app-1
    networks:
      - metrics

  demo-app-2:
    image: varoon10/prometheus-demo-service
    ports: 
      - 8081:8080
    container_name: demo-app-2
    networks:
      - metrics

  demo-app-3:
    image: varoon10/prometheus-demo-service
    ports: 
      - 8082:8080
    container_name: demo-app-3
    networks:
      - metrics

networks:
  metrics:
    name: metrics