services:

  prometheus:
    image: prom/prometheus:v2.45.0
    ports: 
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - metrics

networks:
  metrics:
    name: metrics